# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        MainWindow.setMouseTracking(True)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 0, 161, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("6641c94e15a0be37af49a4250386c03e.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pb_login = QtWidgets.QPushButton(self.centralwidget)
        self.pb_login.setGeometry(QtCore.QRect(150, 250, 171, 31))
        self.pb_login.setObjectName("pb_login")
        self.pb_forgot = QtWidgets.QPushButton(self.centralwidget)
        self.pb_forgot.setGeometry(QtCore.QRect(180, 290, 101, 23))
        self.pb_forgot.setObjectName("pb_forgot")
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(170, 170, 133, 20))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(170, 210, 133, 20))
        self.lineEdit_password.setMouseTracking(False)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pb_show_data = QtWidgets.QPushButton(self.centralwidget)
        self.pb_show_data.setGeometry(QtCore.QRect(20, 370, 101, 23))
        self.pb_show_data.setObjectName("pb_show_data")
        self.lb_info = QtWidgets.QLabel(self.centralwidget)
        self.lb_info.setGeometry(QtCore.QRect(190, 130, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb_info.setFont(font)
        self.lb_info.setObjectName("lb_info")
        self.pb_search = QtWidgets.QPushButton(self.centralwidget)
        self.pb_search.setGeometry(QtCore.QRect(190, 370, 101, 23))
        self.pb_search.setObjectName("pb_search")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_login.setText(_translate("MainWindow", "Log in"))
        self.pb_forgot.setText(_translate("MainWindow", "Forgot Password"))
        self.label_2.setText(_translate("MainWindow", "Username or Telephone:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.pb_show_data.setText(_translate("MainWindow", "Show My Datas"))
        self.lb_info.setText(_translate("MainWindow", "Welcome"))
        self.pb_search.setText(_translate("MainWindow", "Serach Username"))
